server:
  port: 8082
  servlet:
    context-path: /auth

spring:
  rabbitmq:
    addresses: ${RABBITMQ_URL}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    virtual-host: ${RABBITMQ_VHOST}
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 180000
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: false
        batch_versioned_data: true
        order_insert: true
        order_update: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    open-in-view: false
app:
  read-only: false
  encryption-key:
    HMAC-key-secret: ${HMAC_SECRET_KEY}
  rabbit:
    addresses: ${RABBITMQ_URL}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}
    virtual-host: ${RABBITMQ_VHOST}